# Generated by Django 3.1.7 on 2021-03-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventregistration',
            name='registration_code',
            field=models.PositiveIntegerField(default=654774),
        ),
    ]
