# Generated by Django 3.1.7 on 2021-03-17 20:13
/
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rootapp', '0002_eventregistration_registration_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='registration_code',
            field=models.PositiveIntegerField(default=824448),
        ),
    ]
