#!/bin/bash
# setup after first pull
virtualenv env
source env/bin/activate
pip3 install -r requirements.txt
cd magicevents/
python manage.py makemigrations
python manage.py migrate
python manage.py createsuperuser
